apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-db
spec:
  selector:
    matchLabels:
      app: myapp-db
  template:
    metadata:
      labels:
        app: myapp-db
    spec:
      containers:
      - name: myapp-db
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: db-password
        volumeMounts:
          - name: mysql-data
            mountPath: "/var/lib/mysql"
            subPath: "mysql"
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data-disk
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-db-service
spec:
  selector:
    app: myapp-db
  ports:
  - port: 3306
    targetPort: 3306